_BASE_: config.yaml
SEED: 4
MODEL:
  META_ARCHITECTURE: "CATSeg"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "//home/fywang/Documents/CXRSeg/pretrained/resnet/R-101.pkl"
  PIXEL_MEAN: [0, 0, 0]
  PIXEL_STD: [255, 255, 255]
  CLIP_PIXEL_MEAN: [0, 0, 0]
  CLIP_PIXEL_STD: [255, 255, 255]
  SEM_SEG_HEAD:
    NAME: "CATSegHead"
    IN_FEATURES: ["res2", "res3", "res4"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 14
    DATASET_DIR: "/disk1/fywang/CXR_dataset"
    TRAIN_CLASS_JSON: "/disk1/fywang/CXR_dataset/mask/MaCheX/train_categories.json"
    TEST_CLASS_JSON: "/disk1/fywang/CXR_dataset/mask/MaCheX/val_chexlocalize_categories.json"
    MEDCLIP_CKPT: "/disk1/fywang/CXRSEG/logs/medclip/ckpts/MedCLIP_2024_04_30_12_11_00/epoch=8-step=3780.ckpt"
    CLIP_FINETUNE: "full"
    PROMPT_DEPTH: 0
    PROMPT_LENGTH: 0
    TEXT_GUIDANCE_DIM: 0
    TEXT_GUIDANCE_PROJ_DIM: 0
    APPEARANCE_GUIDANCE_DIM: 0
    APPEARANCE_GUIDANCE_PROJ_DIM: 0
    DECODER_DIMS: [32, 16]
    DECODER_GUIDANCE_DIMS: [0]
    DECODER_GUIDANCE_PROJ_DIMS: [0, 0]
    NUM_LAYERS: 1
    NUM_HEADS: 4
    HIDDEN_DIMS: 64
    POOLING_SIZES: [2, 2]
    FEATURE_RESOLUTION: [16, 16]
    WINDOW_SIZES: 16
    ATTENTION_TYPE: "linear"
DATASETS:
  TRAIN: ("machx_train",)
  TEST: ("chexlocalize_val",)
INPUT:
  MIN_SIZE_TRAIN: (512, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 512)
  SIZE_DIVISIBILITY: 512 
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "cxrseg_semantic"
SOLVER:
  IMS_PER_BATCH: 64
  TEST_IMS_PER_BATCH: 1
  LR_SCHEDULER_NAME: WarmupMultiStepLR
  BASE_LR: 0.00002
  GAMMA: 1.
  MAX_ITER: 500
  BACKBONE_MULTIPLIER: 0.0
  CLIP_MULTIPLIER: 0.01
  CHECKPOINT_PERIOD: 100
TEST:
  EVAL_PERIOD: 100